In [2]:
# requirements
from pymongo import MongoClient

import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.neural_network import MLPClassifier

from sklearn.decomposition import PCA

import joblib

import tqdm
import heapq

In [3]:
# MongoDB 연결
client = MongoClient("mongodb://localhost:3999/")

In [4]:
# DB 불러오기
matchup_statistics_db = client["matchup_statistics_db"]  # summoners, indicators, matches

In [5]:
for collection_name in matchup_statistics_db.list_collection_names():
    print(collection_name)
    collection = matchup_statistics_db["summoners"]

    documents = collection.find()
    cnt = 0

    for document in tqdm.tqdm(documents):
        print(document)
        break
        cnt += 1

    print(cnt)

summoners


0it [00:00, ?it/s]


{'_id': 't3C2JzNt9v8ypQ3PtL7v4c6VNvn-QdDDnm8-Pcnllyd65xPT', 'account': {'puuid': 'YgzlaLXtIVvhGHRrrRargPwFhxK4bodWePdVNFob_p4eFYbaiO9UTsyUfpAPkJaPaU9hJn6w9N0L5w', 'gameName': '데프트룰러구마유시김기영', 'tagLine': 'KR0'}, 'summonerDetail': {'puuid': 'YgzlaLXtIVvhGHRrrRargPwFhxK4bodWePdVNFob_p4eFYbaiO9UTsyUfpAPkJaPaU9hJn6w9N0L5w', 'accountId': '8yGK0p-mJWzLMpNRRLBPfE-fem58RB1FlgjRLUebFBDqRT7jYzj9i4vM', 'name': '질수록단단해져', 'profileIconId': 6213, 'revisionDate': 1711577276075, 'summonerLevel': 167}, 'league': {'leagueId': 'a641f839-6c70-4e6d-be1f-9255e5ea82d0', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'DIAMOND', 'rank': 'I', 'summonerId': 't3C2JzNt9v8ypQ3PtL7v4c6VNvn-QdDDnm8-Pcnllyd65xPT', 'summonerName': '질수록단단해져', 'leaguePoints': '37', 'wins': '144', 'losses': '138', 'veteran': 'false', 'inactive': 'false', 'freshBlood': 'true', 'hotStreak': 'false'}, 'matchIds': ['KR_7005161680', 'KR_7003979996', 'KR_7003981392', 'KR_7002755648', 'KR_7001520207', 'KR_7001505617', 'KR_6999799911', 'KR_6999792065', 'K

0it [00:00, ?it/s]

{'_id': 't3C2JzNt9v8ypQ3PtL7v4c6VNvn-QdDDnm8-Pcnllyd65xPT', 'account': {'puuid': 'YgzlaLXtIVvhGHRrrRargPwFhxK4bodWePdVNFob_p4eFYbaiO9UTsyUfpAPkJaPaU9hJn6w9N0L5w', 'gameName': '데프트룰러구마유시김기영', 'tagLine': 'KR0'}, 'summonerDetail': {'puuid': 'YgzlaLXtIVvhGHRrrRargPwFhxK4bodWePdVNFob_p4eFYbaiO9UTsyUfpAPkJaPaU9hJn6w9N0L5w', 'accountId': '8yGK0p-mJWzLMpNRRLBPfE-fem58RB1FlgjRLUebFBDqRT7jYzj9i4vM', 'name': '질수록단단해져', 'profileIconId': 6213, 'revisionDate': 1711577276075, 'summonerLevel': 167}, 'league': {'leagueId': 'a641f839-6c70-4e6d-be1f-9255e5ea82d0', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'DIAMOND', 'rank': 'I', 'summonerId': 't3C2JzNt9v8ypQ3PtL7v4c6VNvn-QdDDnm8-Pcnllyd65xPT', 'summonerName': '질수록단단해져', 'leaguePoints': '37', 'wins': '144', 'losses': '138', 'veteran': 'false', 'inactive': 'false', 'freshBlood': 'true', 'hotStreak': 'false'}, 'matchIds': ['KR_7005161680', 'KR_7003979996', 'KR_7003981392', 'KR_7002755648', 'KR_7001520207', 'KR_7001505617', 'KR_6999799911', 'KR_6999792065', 'K

0it [00:00, ?it/s]

{'_id': 't3C2JzNt9v8ypQ3PtL7v4c6VNvn-QdDDnm8-Pcnllyd65xPT', 'account': {'puuid': 'YgzlaLXtIVvhGHRrrRargPwFhxK4bodWePdVNFob_p4eFYbaiO9UTsyUfpAPkJaPaU9hJn6w9N0L5w', 'gameName': '데프트룰러구마유시김기영', 'tagLine': 'KR0'}, 'summonerDetail': {'puuid': 'YgzlaLXtIVvhGHRrrRargPwFhxK4bodWePdVNFob_p4eFYbaiO9UTsyUfpAPkJaPaU9hJn6w9N0L5w', 'accountId': '8yGK0p-mJWzLMpNRRLBPfE-fem58RB1FlgjRLUebFBDqRT7jYzj9i4vM', 'name': '질수록단단해져', 'profileIconId': 6213, 'revisionDate': 1711577276075, 'summonerLevel': 167}, 'league': {'leagueId': 'a641f839-6c70-4e6d-be1f-9255e5ea82d0', 'queueType': 'RANKED_SOLO_5x5', 'tier': 'DIAMOND', 'rank': 'I', 'summonerId': 't3C2JzNt9v8ypQ3PtL7v4c6VNvn-QdDDnm8-Pcnllyd65xPT', 'summonerName': '질수록단단해져', 'leaguePoints': '37', 'wins': '144', 'losses': '138', 'veteran': 'false', 'inactive': 'false', 'freshBlood': 'true', 'hotStreak': 'false'}, 'matchIds': ['KR_7005161680', 'KR_7003979996', 'KR_7003981392', 'KR_7002755648', 'KR_7001520207', 'KR_7001505617', 'KR_6999799911', 'KR_6999792065', 'K

In [7]:
silver_users = []

for summoner in matchup_statistics_db["summoners"].find():
    if summoner["league"]["tier"] == "SILVER" or summoner["league"]["tier"] == "GOLD" or summoner["league"]["tier"] == "BRONZE" or summoner["league"]["tier"] == "IRON":
        silver_users.append(summoner["_id"])

print(len(silver_users))
print(silver_users[0])

17287
Ar_KKTRQ4khe-Lm8iDZzy5GLzag_4QfvTCZyXkQYodvTVBmx


In [8]:
# 학습 데이터 추출

# collection 불러오기
indicators = matchup_statistics_db["indicators"].find()

# 학습 데이터
x = []
y = []

summoners = []

times = 0
all_zero = 0


# 결측치 처리 - 추후에는 평균 값으로 입력
def imputation(datas, indicator, record, record_detail):
    global times

    if datas[indicator][record].get(record_detail):
        return datas[indicator][record].get(record_detail)
    else:
        times += 1
        return 0

# 데이터 추출
for indicator in indicators:
    if indicator["_id"] not in silver_users:
        continue

    for match_indicator in indicator["matchIndicators"]:
        summoner = {}

        summoner["csDiffer"] = match_indicator["laneIndicator"]["basicWeight"]["csDiffer"]
        summoner["expDiffer"] = match_indicator["laneIndicator"]["basicWeight"]["expDiffer"]
        summoner["turretPlateDestroyDiffer"] = match_indicator["laneIndicator"]["basicWeight"]["turretPlateDestroyDiffer"]
        summoner["dealDiffer"] = imputation(match_indicator, "laneIndicator", "aggresiveLaneAbilility", "dealDiffer")

        summoner["turretKillsPerDeaths"] = match_indicator["macroIndicator"]["splitPoint"]["turretKillsPerDeaths"]
        summoner["damageDealtToTurretsPerTeamTotalTowerDamageDone"] = match_indicator["macroIndicator"]["splitPoint"]["damageDealtToTurretsPerTeamTotalTowerDamageDone"]

        summoner["totalTimeCCingOthersPerTotalDamageTaken"] = match_indicator["macroIndicator"]["initiatingPoint"]["totalTimeCCingOthersPerTotalDamageTaken"]
        summoner["totalDamageTakenPerTeamTotalDamageTaken"] = match_indicator["macroIndicator"]["initiatingPoint"]["totalDamageTakenPerTeamTotalDamageTaken"]
        summoner["damageSelfMitigatedPerTotalDamageTaken"] = match_indicator["macroIndicator"]["initiatingPoint"]["damageSelfMitigatedPerTotalDamageTaken"]

        summoner["visionScorePerDeath"] = match_indicator["macroIndicator"]["visionPoint"]["visionScorePerDeath"]
        summoner["totalJungleObjectivePerGameDuration"] = match_indicator["macroIndicator"]["jungleHoldPoint"]["totalJungleObjectivePerGameDuration"]

        summoner["getObjectiveDifferPerGameDuration"] = match_indicator["macroIndicator"]["objectivePoint"]["getObjectiveDifferPerGameDuration"]

        summoner["damagePerMinute"] = match_indicator["macroIndicator"]["totalDealPoint"]["damagePerMinute"]
        summoner["dealPerGold"] = imputation(match_indicator, "macroIndicator", "totalDealPoint", "dealPerGold")
        summoner["teamDamagePercentage"] = imputation(match_indicator, "macroIndicator", "totalDealPoint", "teamDamagePercentage")

        if match_indicator["metadata"]["laneInfo"].get("teamPosition") == "TOP":
            pass


        is_all_zero = True
        idx = 0

        for key, value in summoner.items():
            if value != 0:
                is_all_zero = False
                break 
                
        if is_all_zero is False:

            if match_indicator["metadata"]["isWin"] is True:
                y.append(1)
            else:
                y.append(0)

            summoners.append(summoner)

In [9]:
df = pd.DataFrame(summoners)
df

csDiffer  expDiffer  turretPlateDestroyDiffer  dealDiffer  \
0            -37      -1889                  1.666667       -3018   
1            -31       -892                  5.000000       -5154   
2            -55       -532                  3.000000       -2751   
3            -23       -304                 -1.000000       -5855   
4              8        523                 -2.000000        5511   
...          ...        ...                       ...         ...   
320656        70       1770                 -5.000000        1767   
320657        18       1193                  1.333333        2455   
320658        26       2291                 -2.000000        4351   
320659         7       -694                  2.000000       -2673   
320660        18        264                  0.666667       -2393   

        turretKillsPerDeaths  damageDealtToTurretsPerTeamTotalTowerDamageDone  \
0                          0                                                0   
1                          0                                            41462   
2                      16666                                             5680   
3                          0                                            34319   
4                      33333                                            38699   
...                      ...                                              ...   
320656                 83333                                            42047   
320657                 20000                                            18660   
320658                     0                                            13585   
320659                     0                                            12921   
320660                     0                                            15271   

        totalTimeCCingOthersPerTotalDamageTaken  \
0                                            27   
1                                             0   
2                                            13   
3                                             8   
4                                            26   
...                                         ...   
320656                                      113   
320657                                       86   
320658                                      106   
320659                                        0   
320660                                      119   

        totalDamageTakenPerTeamTotalDamageTaken  \
0                                         30170   
1                                         11947   
2                                         10681   
3                                         17057   
4                                         11329   
...                                         ...   
320656                                    19221   
320657                                    28845   
320658                                    26460   
320659                                    17350   
320660                                    30715   

        damageSelfMitigatedPerTotalDamageTaken  visionScorePerDeath  \
0                                        58618               260000   
1                                        38415               300000   
2                                        45467               450000   
3                                        53257               242857   
4                                        74773              1400000   
...                                        ...                  ...   
320656                                  123841               450000   
320657                                  114744               680000   
320658                                  121087               533333   
320659                                   50990               155555   
320660                                  144230               475000   

        totalJungleObjectivePerGameDuration  \
0                                         0   
1                                

In [10]:
# PCA
df_normalized = (df - df.min()) / (df.max() - df.min())

In [11]:
scaler = StandardScaler()
x = df_normalized.to_numpy()
x_scaled = scaler.fit_transform(x)

In [12]:
print(x[0])

[4.03448276e-01 3.84128847e-01 6.66666667e-01 4.80861995e-01
 0.00000000e+00 0.00000000e+00 2.38235995e-04 5.27419891e-01
 4.80598711e-02 2.01550388e-02 0.00000000e+00 3.21500000e-01
 3.87035872e-02 7.54666457e-02 1.15233087e-01]


In [13]:
parameter_space = {
    'hidden_layer_sizes': [(50,), (100,), (50, 50), (100, 50)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
}

In [14]:
# mlp = MLPClassifier(hidden_layer_sizes=(75, ), max_iter=500, activation='relu', solver='adam', random_state=42, alpha=0.00001, verbose=True)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
mlp = MLPClassifier(max_iter=500)
random_search = RandomizedSearchCV(mlp, param_distributions=parameter_space, n_iter=10, cv=5, verbose=2, random_state=42, n_jobs=-1)
random_search.fit(x_train, y_train)
#mlp.fit(x_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


RandomizedSearchCV(cv=5, estimator=MLPClassifier(max_iter=500), n_jobs=-1,
                   param_distributions={'activation': ['tanh', 'relu'],
                                        'alpha': [0.0001, 0.05],
                                        'hidden_layer_sizes': [(50,), (100,),
                                                               (50, 50),
                                                               (100, 50)],
                                        'learning_rate': ['constant',
                                                          'adaptive'],
                                        'solver': ['sgd', 'adam']},
                   random_state=42, verbose=2)

In [15]:
print("최적의 하이퍼파라미터:", random_search.best_params_)
print("최고 점수:", random_search.best_score_)

최적의 하이퍼파라미터: {'solver': 'adam', 'learning_rate': 'constant', 'hidden_layer_sizes': (100,), 'alpha': 0.0001, 'activation': 'tanh'}
최고 점수: 0.8678272941809541


In [16]:
mlp = MLPClassifier(hidden_layer_sizes=(100, ), max_iter=500, activation='tanh', solver='adam', random_state=42, alpha = 0.0001, learning_rate = 'constant', verbose=True)
mlp.fit(x_train, y_train)

Iteration 1, loss = 0.40839288
Iteration 2, loss = 0.34788248
Iteration 3, loss = 0.34501210
Iteration 4, loss = 0.34414661
Iteration 5, loss = 0.34318294
Iteration 6, loss = 0.34153284
Iteration 7, loss = 0.33913548
Iteration 8, loss = 0.33535500
Iteration 9, loss = 0.33282514
Iteration 10, loss = 0.33146600
Iteration 11, loss = 0.33033348
Iteration 12, loss = 0.32947711
Iteration 13, loss = 0.32916375
Iteration 14, loss = 0.32780853
Iteration 15, loss = 0.32732867
Iteration 16, loss = 0.32686471
Iteration 17, loss = 0.32626052
Iteration 18, loss = 0.32555257
Iteration 19, loss = 0.32512235
Iteration 20, loss = 0.32439893
Iteration 21, loss = 0.32394706
Iteration 22, loss = 0.32323766
Iteration 23, loss = 0.32258929
Iteration 24, loss = 0.32201718
Iteration 25, loss = 0.32140910
Iteration 26, loss = 0.32112309
Iteration 27, loss = 0.32043744
Iteration 28, loss = 0.32013195
Iteration 29, loss = 0.31950597
Iteration 30, loss = 0.31887396
Iteration 31, loss = 0.31834510
Iteration 32, los

MLPClassifier(activation='tanh', max_iter=500, random_state=42, verbose=True)

In [17]:
joblib.dump(mlp, 'winning_models/silver_model.pkl')

['winning_models/silver_model.pkl']

In [99]:
max_heapq = []

probabilities = mlp.predict_proba(x_test)
cnt = 0
total = 0
for i, probability in enumerate(probabilities):
    heapq.heappush(max_heapq, (-probability[1], i))
    total += 1
    if probability[1] > 0.9:
        cnt += 1
    # print(f"{i}번째 승리확률 : {probability[1]}")

print(total)
print(cnt)

for _ in range(5):
    print(heapq.heappop(max_heapq))

[[0.5480427  0.62149135 0.5        ... 0.13750787 0.296798   0.25519632]
 [0.59786477 0.60837823 0.3        ... 0.27092511 0.38785193 0.63389444]
 [0.51601423 0.52211511 0.5        ... 0.14317181 0.24541629 0.22681683]
 ...
 [0.61209964 0.64615821 0.1        ... 0.34833228 0.40505777 0.61567914]
 [0.59074733 0.57293734 0.5        ... 0.13624921 0.25820276 0.2334923 ]
 [0.49466192 0.49907854 0.6        ... 0.23348018 0.29540348 0.39018069]]
48551
12356
(-0.9999999839766744, 19896)
(-0.9999999779354829, 7970)
(-0.9999999652883452, 8818)
(-0.9999999592109347, 46684)
(-0.9999999435980574, 44015)
