In [2]:
# requirements
from pymongo import MongoClient

import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.neural_network import MLPClassifier

from sklearn.decomposition import PCA

import joblib

import tqdm
import heapq
import json

In [3]:
# MongoDB 연결
client = MongoClient("mongodb://localhost:3999/")

In [4]:
# DB 불러오기
matchup_statistics_db = client["matchup_statistics_db"]  # summoners, indicators, matches

In [5]:
for collection_name in matchup_statistics_db.list_collection_names():
    print(collection_name)
    collection = matchup_statistics_db["indicators"]

    documents = collection.find()
    cnt = 0

    for document in tqdm.tqdm(documents):
        print(document)
        break
        cnt += 1

    print(cnt)

summoners


0it [00:00, ?it/s]


{'_id': 't3C2JzNt9v8ypQ3PtL7v4c6VNvn-QdDDnm8-Pcnllyd65xPT', 'matchIndicators': [{'matchId': 'KR_6992198203', 'metadata': {'laneInfo': {'teamPosition': 'BOTTOM', 'isBottomLane': True, 'myTeamId': 100, 'myLaneNumber': 4, 'oppositeLaneNumber': 9, 'myBottomDuoNumber': 5, 'oppositeBottomDuoNumber': 10}, 'timeInfo': {'gameDuration': 1663, 'startTime': 1710722466095, 'endTime': 1710724129616}, 'isFinishedBeforeFifteen': False, 'isOurTeamEarlySurrendered': False, 'isWin': False, 'pingCount': 0, 'champion': 'Smolder'}, 'laneIndicator': {'basicWeight': {'csDiffer': 13, 'expDiffer': 760, 'turretPlateDestroyDiffer': 3.0, 'supportItemFinishedTimeDiffer': 0}, 'aggresiveLaneAbilility': {'dealDiffer': -4025, 'soloKillDiffer': 0, 'duoKillDiffer': -2}, '_class': 'com.ssafy.matchup_statistics.indicator.entity.match.beginning.BtmIndicator'}, 'macroIndicator': {'splitPoint': {'turretKillsPerDeaths': 0, 'damageDealtToTurretsPerTotalDamageDealt': 430, 'damageDealtToTurretsPerTeamTotalTowerDamageDone': 24838}

0it [00:00, ?it/s]


{'_id': 't3C2JzNt9v8ypQ3PtL7v4c6VNvn-QdDDnm8-Pcnllyd65xPT', 'matchIndicators': [{'matchId': 'KR_6992198203', 'metadata': {'laneInfo': {'teamPosition': 'BOTTOM', 'isBottomLane': True, 'myTeamId': 100, 'myLaneNumber': 4, 'oppositeLaneNumber': 9, 'myBottomDuoNumber': 5, 'oppositeBottomDuoNumber': 10}, 'timeInfo': {'gameDuration': 1663, 'startTime': 1710722466095, 'endTime': 1710724129616}, 'isFinishedBeforeFifteen': False, 'isOurTeamEarlySurrendered': False, 'isWin': False, 'pingCount': 0, 'champion': 'Smolder'}, 'laneIndicator': {'basicWeight': {'csDiffer': 13, 'expDiffer': 760, 'turretPlateDestroyDiffer': 3.0, 'supportItemFinishedTimeDiffer': 0}, 'aggresiveLaneAbilility': {'dealDiffer': -4025, 'soloKillDiffer': 0, 'duoKillDiffer': -2}, '_class': 'com.ssafy.matchup_statistics.indicator.entity.match.beginning.BtmIndicator'}, 'macroIndicator': {'splitPoint': {'turretKillsPerDeaths': 0, 'damageDealtToTurretsPerTotalDamageDealt': 430, 'damageDealtToTurretsPerTeamTotalTowerDamageDone': 24838}

0it [00:00, ?it/s]

{'_id': 't3C2JzNt9v8ypQ3PtL7v4c6VNvn-QdDDnm8-Pcnllyd65xPT', 'matchIndicators': [{'matchId': 'KR_6992198203', 'metadata': {'laneInfo': {'teamPosition': 'BOTTOM', 'isBottomLane': True, 'myTeamId': 100, 'myLaneNumber': 4, 'oppositeLaneNumber': 9, 'myBottomDuoNumber': 5, 'oppositeBottomDuoNumber': 10}, 'timeInfo': {'gameDuration': 1663, 'startTime': 1710722466095, 'endTime': 1710724129616}, 'isFinishedBeforeFifteen': False, 'isOurTeamEarlySurrendered': False, 'isWin': False, 'pingCount': 0, 'champion': 'Smolder'}, 'laneIndicator': {'basicWeight': {'csDiffer': 13, 'expDiffer': 760, 'turretPlateDestroyDiffer': 3.0, 'supportItemFinishedTimeDiffer': 0}, 'aggresiveLaneAbilility': {'dealDiffer': -4025, 'soloKillDiffer': 0, 'duoKillDiffer': -2}, '_class': 'com.ssafy.matchup_statistics.indicator.entity.match.beginning.BtmIndicator'}, 'macroIndicator': {'splitPoint': {'turretKillsPerDeaths': 0, 'damageDealtToTurretsPerTotalDamageDealt': 430, 'damageDealtToTurretsPerTeamTotalTowerDamageDone': 24838}

In [22]:
division = {"I": 1, "II": 2, "III": 3, "IV": 4}

emerald_users = []
my_rank = 1

# or (summoner["league"]["tier"] == "DIAMOND" and summoner["league"]["rank"] == "IV")

for summoner in matchup_statistics_db["summoners"].find():
    if summoner["league"]["tier"] == "EMERALD" or summoner["league"]["tier"] == "PLATINUM" or (summoner["league"]["tier"] == "DIAMOND" and summoner["league"]["rank"] == "IV") or (summoner["league"]["tier"] == "DIAMOND" and division[summoner["league"]["rank"]] >= 3):
        emerald_users.append(summoner["_id"])

print(len(emerald_users))
print(emerald_users[0])

10560
_PPQgamYvwrjkM_IhALfVWSLlOzOcLh0sFn2Vtn5erGfnSBr


In [23]:
# 학습 데이터 추출

# collection 불러오기
indicators = matchup_statistics_db["indicators"].find()

# 학습 데이터
x = []
y = []

summoners = []

times = 0
all_zero = 0


# 결측치 처리 - 추후에는 평균 값으로 입력
def imputation(datas, indicator, record, record_detail):
    global times

    if datas[indicator][record].get(record_detail):
        return datas[indicator][record].get(record_detail)
    else:
        times += 1
        return 0

# 데이터 추출
for indicator in indicators:
    if indicator["_id"] not in emerald_users:
        continue

    for match_indicator in indicator["matchIndicators"]:
        summoner = {}

        summoner["csDiffer"] = match_indicator["laneIndicator"]["basicWeight"]["csDiffer"]
        summoner["expDiffer"] = match_indicator["laneIndicator"]["basicWeight"]["expDiffer"]
        summoner["turretPlateDestroyDiffer"] = match_indicator["laneIndicator"]["basicWeight"]["turretPlateDestroyDiffer"]
        summoner["dealDiffer"] = imputation(match_indicator, "laneIndicator", "aggresiveLaneAbilility", "dealDiffer")

        summoner["turretKillsPerDeaths"] = match_indicator["macroIndicator"]["splitPoint"]["turretKillsPerDeaths"]
        summoner["damageDealtToTurretsPerTeamTotalTowerDamageDone"] = match_indicator["macroIndicator"]["splitPoint"]["damageDealtToTurretsPerTeamTotalTowerDamageDone"]

        summoner["totalTimeCCingOthersPerTotalDamageTaken"] = match_indicator["macroIndicator"]["initiatingPoint"]["totalTimeCCingOthersPerTotalDamageTaken"]
        summoner["totalDamageTakenPerTeamTotalDamageTaken"] = match_indicator["macroIndicator"]["initiatingPoint"]["totalDamageTakenPerTeamTotalDamageTaken"]
        summoner["damageSelfMitigatedPerTotalDamageTaken"] = match_indicator["macroIndicator"]["initiatingPoint"]["damageSelfMitigatedPerTotalDamageTaken"]

        summoner["visionScorePerDeath"] = match_indicator["macroIndicator"]["visionPoint"]["visionScorePerDeath"]
        summoner["totalJungleObjectivePerGameDuration"] = match_indicator["macroIndicator"]["jungleHoldPoint"]["totalJungleObjectivePerGameDuration"]

        summoner["getObjectiveDifferPerGameDuration"] = match_indicator["macroIndicator"]["objectivePoint"]["getObjectiveDifferPerGameDuration"]

        summoner["damagePerMinute"] = match_indicator["macroIndicator"]["totalDealPoint"]["damagePerMinute"]
        summoner["dealPerGold"] = imputation(match_indicator, "macroIndicator", "totalDealPoint", "dealPerGold")
        summoner["teamDamagePercentage"] = imputation(match_indicator, "macroIndicator", "totalDealPoint", "teamDamagePercentage")

        if match_indicator["metadata"]["laneInfo"].get("teamPosition") == "TOP":
            pass


        is_all_zero = True
        idx = 0

        for key, value in summoner.items():
            if value != 0:
                is_all_zero = False
                break 
                
        if is_all_zero is False:

            if match_indicator["metadata"]["isWin"] is True:
                y.append(1)
            else:
                y.append(0)

            summoners.append(summoner)

In [24]:
df = pd.DataFrame(summoners)
df

csDiffer  expDiffer  turretPlateDestroyDiffer  dealDiffer  \
0             31       2468                      -3.0        5909   
1             -4       -422                       0.0       -2846   
2            -11       -312                      -1.0       -2370   
3              0       -400                       0.0       -1639   
4            -12      -1491                       0.0         150   
...          ...        ...                       ...         ...   
203652       -22       -975                       0.0         374   
203653         3        639                       0.0       -2168   
203654        -8       -338                       0.0        4562   
203655         4        235                       0.0        4169   
203656        -3         55                       0.0        -618   

        turretKillsPerDeaths  damageDealtToTurretsPerTeamTotalTowerDamageDone  \
0                     200000                                            43972   
1                          0                                             3321   
2                          0                                            65478   
3                          0                                                0   
4                          0                                            20408   
...                      ...                                              ...   
203652                     0                                                0   
203653                     0                                                0   
203654                     0                                             5541   
203655                     0                                             2742   
203656                     0                                                0   

        totalTimeCCingOthersPerTotalDamageTaken  \
0                                            38   
1                                            92   
2                                            24   
3                                           166   
4                                             0   
...                                         ...   
203652                                      143   
203653                                      292   
203654                                       28   
203655                                      193   
203656                                      228   

        totalDamageTakenPerTeamTotalDamageTaken  \
0                                         17405   
1                                         13441   
2                                         17249   
3                                         15252   
4                                         17363   
...                                         ...   
203652                                    16661   
203653                                    16979   
203654                                    18693   
203655                                    17928   
203656                                    15244   

        damageSelfMitigatedPerTotalDamageTaken  visionScorePerDeath  \
0                                        44349               433333   
1                                        56697              1200000   
2                                        44969               550000   
3                                        96235               960000   
4                                        49584               166666   
...                                        ...                  ...   
203652                                   71062               666666   
203653                                  104833               977777   
203654                                   99114               381818   
203655                                   55385               516666   
203656                                   92890              1366666   

        totalJungleObjectivePerGameDuration  \
0                                       593   
1                                

In [25]:
# PCA
df_normalized = (df - df.min()) / (df.max() - df.min())

In [26]:
scaler = StandardScaler()
x = df_normalized.to_numpy()
x_scaled = scaler.fit_transform(x)

In [51]:
print(x[0])

[4.03448276e-01 3.84128847e-01 6.66666667e-01 5.00091767e-01
 0.00000000e+00 0.00000000e+00 2.38235995e-04 5.27419891e-01
 4.80598711e-02 2.11382114e-02 0.00000000e+00 3.21500000e-01
 3.87035872e-02 7.54666457e-02 1.15233087e-01]


In [60]:
parameter_space = {
    'hidden_layer_sizes': [(50,), (100,), (50, 50), (100, 50)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
}

In [16]:
# mlp = MLPClassifier(hidden_layer_sizes=(75, ), max_iter=500, activation='relu', solver='adam', random_state=42, alpha=0.00001, verbose=True)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
mlp = MLPClassifier(max_iter=500)
random_search = RandomizedSearchCV(mlp, param_distributions=parameter_space, n_iter=10, cv=5, verbose=2, random_state=42, n_jobs=-1)
random_search.fit(x_train, y_train)
#mlp.fit(x_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


RandomizedSearchCV(cv=5, estimator=MLPClassifier(max_iter=500), n_jobs=-1,
                   param_distributions={'activation': ['tanh', 'relu'],
                                        'alpha': [0.0001, 0.05],
                                        'hidden_layer_sizes': [(50,), (100,),
                                                               (50, 50),
                                                               (100, 50)],
                                        'learning_rate': ['constant',
                                                          'adaptive'],
                                        'solver': ['sgd', 'adam']},
                   random_state=42, verbose=2)

In [17]:
print("최적의 하이퍼파라미터:", random_search.best_params_)
print("최고 점수:", random_search.best_score_)

최적의 하이퍼파라미터: {'solver': 'adam', 'learning_rate': 'constant', 'hidden_layer_sizes': (100,), 'alpha': 0.0001, 'activation': 'tanh'}
최고 점수: 0.8688754608747429


In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
mlp = MLPClassifier(hidden_layer_sizes=(100, ), max_iter=500, activation='tanh', solver='adam', random_state=42, alpha = 0.0001, learning_rate = 'constant', verbose=True)
mlp.fit(x, y)

Iteration 1, loss = 0.41120910
Iteration 2, loss = 0.33481961
Iteration 3, loss = 0.32978521
Iteration 4, loss = 0.32921440
Iteration 5, loss = 0.32839629
Iteration 6, loss = 0.32726644


In [21]:
joblib.dump(mlp, 'models/winning/emerald_1_model.pkl')

['models/winning/emerald_model.pkl']

In [99]:
max_heapq = []

probabilities = mlp.predict_proba(x_test)
cnt = 0
total = 0
for i, probability in enumerate(probabilities):
    heapq.heappush(max_heapq, (-probability[1], i))
    total += 1
    if probability[1] > 0.9:
        cnt += 1
    # print(f"{i}번째 승리확률 : {probability[1]}")

print(total)
print(cnt)

for _ in range(5):
    print(heapq.heappop(max_heapq))

[[0.5480427  0.62149135 0.5        ... 0.13750787 0.296798   0.25519632]
 [0.59786477 0.60837823 0.3        ... 0.27092511 0.38785193 0.63389444]
 [0.51601423 0.52211511 0.5        ... 0.14317181 0.24541629 0.22681683]
 ...
 [0.61209964 0.64615821 0.1        ... 0.34833228 0.40505777 0.61567914]
 [0.59074733 0.57293734 0.5        ... 0.13624921 0.25820276 0.2334923 ]
 [0.49466192 0.49907854 0.6        ... 0.23348018 0.29540348 0.39018069]]
48551
12356
(-0.9999999839766744, 19896)
(-0.9999999779354829, 7970)
(-0.9999999652883452, 8818)
(-0.9999999592109347, 46684)
(-0.9999999435980574, 44015)
